package com.varlanv.wrasse.model

/**
 * Wrasse's own mapping of kotlinc's IElementType constants.
 * Rules reference these instead of importing kotlinc types.
 * When kotlinc renames/splits a token type, only the adapter mapping changes.
 */
enum class WNodeType {

    // -- File structure --
    FILE,
    PACKAGE_DIRECTIVE,
    IMPORT_LIST,
    IMPORT_DIRECTIVE,

    // -- Declarations --
    FUN,
    CLASS,
    OBJECT_DECLARATION,
    PROPERTY,
    TYPEALIAS,
    VALUE_PARAMETER_LIST,
    VALUE_PARAMETER,
    TYPE_PARAMETER_LIST,
    TYPE_PARAMETER,
    CLASS_BODY,
    ENUM_ENTRY,
    PRIMARY_CONSTRUCTOR,
    SECONDARY_CONSTRUCTOR,
    PROPERTY_ACCESSOR,

    // -- Modifiers & annotations --
    MODIFIER_LIST,
    ANNOTATION_ENTRY,
    ANNOTATION_TARGET,

    // -- Type references --
    TYPE_REFERENCE,
    USER_TYPE,
    NULLABLE_TYPE,
    FUNCTION_TYPE,
    TYPE_ARGUMENT_LIST,
    TYPE_PROJECTION,

    // -- Expressions --
    BLOCK,
    LAMBDA_EXPRESSION,
    FUNCTION_LITERAL,
    CALL_EXPRESSION,
    VALUE_ARGUMENT_LIST,
    VALUE_ARGUMENT,
    REFERENCE_EXPRESSION,
    DOT_QUALIFIED_EXPRESSION,
    SAFE_ACCESS_EXPRESSION,
    BINARY_EXPRESSION,
    PREFIX_EXPRESSION,
    POSTFIX_EXPRESSION,
    IF,
    WHEN,
    WHEN_ENTRY,
    WHEN_CONDITION_EXPRESSION,
    WHEN_CONDITION_IS_PATTERN,
    FOR,
    WHILE,
    DO_WHILE,
    TRY,
    CATCH,
    FINALLY,
    RETURN,
    THROW,
    BREAK,
    CONTINUE,
    IS_EXPRESSION,
    AS_EXPRESSION,
    OBJECT_LITERAL,
    THIS_EXPRESSION,
    SUPER_EXPRESSION,
    PARENTHESIZED,
    LABELED_EXPRESSION,

    // -- Literals --
    INTEGER_CONSTANT,
    FLOAT_CONSTANT,
    CHARACTER_CONSTANT,
    BOOLEAN_CONSTANT,
    NULL,
    STRING_TEMPLATE,
    LONG_STRING_TEMPLATE_ENTRY,
    SHORT_STRING_TEMPLATE_ENTRY,
    LITERAL_STRING_TEMPLATE_ENTRY,
    ESCAPE_STRING_TEMPLATE_ENTRY,
    OPEN_QUOTE,
    CLOSING_QUOTE,
    REGULAR_STRING_PART,

    // -- Tokens (leaves) --
    IDENTIFIER,
    WHITE_SPACE,
    EOL_COMMENT,
    BLOCK_COMMENT,
    KDOC,
    LPAR,
    RPAR,
    LBRACE,
    RBRACE,
    LBRACKET,
    RBRACKET,
    COMMA,
    DOT,
    SAFE_ACCESS,
    ELVIS,
    RANGE,
    COLONCOLON,
    COLON,
    SEMICOLON,
    ARROW,
    DOUBLE_ARROW,
    EQ,
    EQEQ,
    EXCLEQ,
    LT,
    GT,
    LTEQ,
    GTEQ,
    PLUS,
    MINUS,
    MUL,
    DIV,
    PERC,
    PLUSEQ,
    MINUSEQ,
    MULEQ,
    DIVEQ,
    PERCEQ,
    ANDAND,
    OROR,
    EXCL,
    PLUSPLUS,
    MINUSMINUS,

    // -- Keywords --
    KW_FUN,
    KW_VAL,
    KW_VAR,
    KW_CLASS,
    KW_INTERFACE,
    KW_OBJECT,
    KW_IF,
    KW_ELSE,
    KW_WHEN,
    KW_FOR,
    KW_WHILE,
    KW_DO,
    KW_RETURN,
    KW_THROW,
    KW_BREAK,
    KW_CONTINUE,
    KW_TRY,
    KW_CATCH,
    KW_FINALLY,
    KW_IN,
    KW_IS,
    KW_AS,
    KW_NULL,
    KW_TRUE,
    KW_FALSE,
    KW_THIS,
    KW_SUPER,
    KW_PACKAGE,
    KW_IMPORT,
    KW_PUBLIC,
    KW_PRIVATE,
    KW_PROTECTED,
    KW_INTERNAL,
    KW_OPEN,
    KW_ABSTRACT,
    KW_SEALED,
    KW_DATA,
    KW_OVERRIDE,
    KW_SUSPEND,
    KW_INLINE,
    KW_TAILREC,
    KW_OPERATOR,
    KW_INFIX,
    KW_COMPANION,
    KW_CONST,
    KW_LATEINIT,
    KW_ENUM,
    KW_TYPEALIAS,

    // -- Fallback for unmapped kotlinc types --
    UNKNOWN,
    ;

    companion object {
        @JvmField
        val VALUES: Array<WNodeType> = entries.toTypedArray()

        @JvmField
        val SIZE: Int = VALUES.size
    }
}
